// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/graph_rag/objectbox/document_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1375226805240877433),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(10, 2242935523644388237),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 972273122319329953),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3119376038009702867),
        name: 'sourceDocumentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8993238510852400610),
        name: 'sourceType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7710712493273757491),
        name: 'sourceTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4332801651708320111),
        name: 'textContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7941269056768563021),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4996274118227918974),
        name: 'totalChunks',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 429832700582528760),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 2007474181640120730),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 384,
          neighborsPerNode: 32,
          indexingSearchCount: 200,
          distanceType: 2,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1778164972234610759),
        name: 'ingestionTimestampMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2242935523644388237),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1375226805240877433),
    lastIndexId: const obx_int.IdUid(1, 2007474181640120730),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final sourceDocumentIdOffset = fbb.writeString(object.sourceDocumentId);
        final sourceTitleOffset = object.sourceTitle == null
            ? null
            : fbb.writeString(object.sourceTitle!);
        final textContentOffset = fbb.writeString(object.textContent);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceDocumentIdOffset);
        fbb.addInt64(2, object.sourceType);
        fbb.addOffset(3, sourceTitleOffset);
        fbb.addOffset(4, textContentOffset);
        fbb.addInt64(5, object.chunkIndex);
        fbb.addInt64(6, object.totalChunks);
        fbb.addOffset(7, embeddingOffset);
        fbb.addInt64(8, object.ingestionTimestampMs);
        fbb.addOffset(9, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceDocumentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final totalChunksParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final ingestionTimestampMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final sourceTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = DocumentChunk(
          id: idParam,
          sourceDocumentId: sourceDocumentIdParam,
          sourceType: sourceTypeParam,
          textContent: textContentParam,
          chunkIndex: chunkIndexParam,
          totalChunks: totalChunksParam,
          ingestionTimestampMs: ingestionTimestampMsParam,
          sourceTitle: sourceTitleParam,
          embedding: embeddingParam,
          metadataJson: metadataJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.sourceDocumentId].
  static final sourceDocumentId = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.sourceType].
  static final sourceType = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.sourceTitle].
  static final sourceTitle = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[3],
  );

  /// See [DocumentChunk.textContent].
  static final textContent = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[4],
  );

  /// See [DocumentChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[5],
  );

  /// See [DocumentChunk.totalChunks].
  static final totalChunks = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[6],
  );

  /// See [DocumentChunk.embedding].
  static final embedding = obx.QueryHnswProperty<DocumentChunk>(
    _entities[0].properties[7],
  );

  /// See [DocumentChunk.ingestionTimestampMs].
  static final ingestionTimestampMs = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[8],
  );

  /// See [DocumentChunk.metadataJson].
  static final metadataJson = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[9],
  );
}
